.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitcoinlambo_qt test_bitcoinlambo_qt
clean: FORCE
	$(MAKE) -C .. bitcoinlambo_qt_clean test_bitcoinlambo_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitcoinlambo_qt_check
bitcoinlambo-qt bitcoinlambo-qt.exe: FORCE
	 $(MAKE) -C .. bitcoinlambo_qt
